FROM jenkins/jenkins:lts

# docker file transformada em imagem e esta no dockerhub

# https://hub.docker.com/r/jaummn/jenkins-python-crocodile

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv zip curl msmtp msmtp-mta mailutils && \
    apt-get clean

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean



USER jenkins